"""
live_build.py — build the scene inside a live Blender session through Blender MCP.

Designed to be called through Blender MCP's ``execute_blender_code`` tool:

    import sys; sys.path.append(r"/path/to/repo/scripts")
    import importlib, live_build; importlib.reload(live_build)
    info = live_build.build(r"/path/to/repo/output/<slug>/scene.json",
                            heading=90, sv_xy=(0, -40))
    print(info)

It reuses blender_build.py, so the live session matches the headless output.
"""
import json

import bpy

import blender_build as bb


def build(scene_path, heading=None, sv_xy=(0.0, 0.0), height=2.5, fov=90.0,
          clear=True, standard_view=True):
    """Build the 3D scene in the current Blender session.

    scene_path : path to the scene.json generated by place_to_3d.py
    heading    : when provided (0=N, 90=E, ...), use a street-level camera
                 facing that bearing. When None, use a three-quarter aerial view.
    sv_xy      : street-level camera position in local meters.
    clear      : safely clear the current scene before building when True.
    """
    with open(scene_path) as f:
        scene = json.load(f)

    if clear:
        # Never use read_factory_settings: it unregisters the Blender MCP add-on
        # and terminates the live server. Use the safe object-level clear instead.
        bb.clear_scene()

    cx, cy, R = bb.build_scene(scene)
    street_level = heading is not None
    scene_kind = scene.get("scene_kind", "urban")
    # A physical sky plus an explicit SUN can overexpose aerial views in some
    # Blender/Cycles combinations. Keep it for street-level views only.
    bb.setup_world(sky=street_level)
    if not street_level:
        bb.setup_sun()

    if street_level:
        # Keep the camera outside buildings. Explicitly safe positions are unchanged.
        try:
            import citycamera
            sv_xy, _moved = citycamera.safe_street_point(
                scene, float(sv_xy[0]), float(sv_xy[1]))
        except Exception:
            _moved = False
        bb.setup_streetview_camera(float(heading), float(fov), float(height),
                                   float(sv_xy[0]), float(sv_xy[1]))
    else:
        bb.setup_camera(cx, cy, R)

    if standard_view:
        vs = bpy.context.scene.view_settings
        if street_level:
            # Photographic tone mapping for the physical sky's high dynamic range.
            for vt in ("AgX", "Filmic", "Standard"):
                try:
                    vs.view_transform = vt
                    break
                except TypeError:
                    continue
            try:
                vs.exposure = -1.8
            except Exception:
                pass
        else:
            try:
                vs.view_transform = "Standard"
                vs.exposure = bb.EXPOSURE
            except Exception:
                pass

    return {
        "buildings": len(scene.get("buildings", [])),
        "roads": len(scene.get("roads", [])),
        "areas": len(scene.get("areas", [])),
        "special_features": len(scene.get("special_features", [])),
        "scene_kind": scene_kind,
        "radius_m": round(R, 1),
        "center_latlon": [scene["center"]["lat"], scene["center"]["lon"]],
        "camera_moved_to_safe_point": bool(_moved) if street_level else False,
    }


def building_at(scene_path, x=0.0, y=0.0):
    """Return the building whose footprint contains ``(x, y)``, or None.

    Useful for locating a landmark and replacing it with a detailed model.
    """
    with open(scene_path) as f:
        scene = json.load(f)

    def contains(poly, px, py):
        inside = False
        n = len(poly)
        j = n - 1
        for i in range(n):
            xi, yi = poly[i]
            xj, yj = poly[j]
            if ((yi > py) != (yj > py)) and \
               (px < (xj - xi) * (py - yi) / ((yj - yi) or 1e-9) + xi):
                inside = not inside
            j = i
        return inside

    for b in scene.get("buildings", []):
        if contains(b["footprint"], x, y):
            return {"type": b.get("type"), "height": b["height"],
                    "footprint": b["footprint"]}
    return None
